import { defineConfig } from "vite";
import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

/**
 * This repository is the GitHub Pages user site: https://jannat4k2.github.io/
 * Absolute root assets keep clean, indexable route URLs working from the static
 * route mirrors generated by scripts/generate-static-pages.mjs.
 */
export default defineConfig({
  base: "/",
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [tailwindcss(), viteReact()],
});
